kind: Service
apiVersion: v1
metadata:
  name: django-postgres
  namespace: ${K8S_NAMESPACE}
spec:
  selector:
    app: postgres-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
