kind: Service
apiVersion: v1
metadata:
  name: django-service
  labels:
    app: django-ref-app   
spec:
  selector:
    app: django-ref-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: metrics
  type: NodePort
  
  

